// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXRx-ZnIXKzLUf8sc7sRuVroyShojfgwo',
    appId: '1:509791412313:web:af289fad6d329e40ff5148',
    messagingSenderId: '509791412313',
    projectId: 'hello-a850b',
    authDomain: 'hello-a850b.firebaseapp.com',
    storageBucket: 'hello-a850b.appspot.com',
    measurementId: 'G-Q5PLFC3ZZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBODgPLYYVkiRMyuiC7R9fecewMnY6aPJQ',
    appId: '1:509791412313:android:e779129062fbfd9cff5148',
    messagingSenderId: '509791412313',
    projectId: 'hello-a850b',
    storageBucket: 'hello-a850b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmoILThqLcenKbkXb12h0imsiHDz0LwG0',
    appId: '1:509791412313:ios:3aa4dfbf3cd923d6ff5148',
    messagingSenderId: '509791412313',
    projectId: 'hello-a850b',
    storageBucket: 'hello-a850b.appspot.com',
    iosClientId: '509791412313-7hhbgejm4fp67rp32pim46euu45lj7ho.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
